"""add cuped covariate and bandit allocation mode

Revision ID: 2ca9f31f49a2
Revises: dd3f7ea4c121
Create Date: 2026-08-05 19:48:40.801989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca9f31f49a2'
down_revision: Union[str, Sequence[str], None] = 'dd3f7ea4c121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiments', 'allocation_mode',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'fixed'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiments', 'allocation_mode',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'fixed'::character varying"))
    # ### end Alembic commands ###
