"""initial schema

Revision ID: 3da6df394e1f
Revises: 
Create Date: 2026-07-13 12:15:18.253276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da6df394e1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversions', sa.Column('experiment_id', sa.UUID(), nullable=False))
    op.add_column('conversions', sa.Column('variant_id', sa.UUID(), nullable=False))
    op.add_column('conversions', sa.Column('visitor_id', sa.UUID(), nullable=False))
    op.add_column('conversions', sa.Column('goal', sa.String(), nullable=False))
    op.create_foreign_key(None, 'conversions', 'variants', ['variant_id'], ['id'])
    op.create_foreign_key(None, 'conversions', 'experiments', ['experiment_id'], ['id'])
    op.create_foreign_key(None, 'conversions', 'visitors', ['visitor_id'], ['id'])
    op.drop_column('conversions', 'user_id')
    op.add_column('events', sa.Column('experiment_id', sa.UUID(), nullable=False))
    op.add_column('events', sa.Column('variant_id', sa.UUID(), nullable=False))
    op.add_column('events', sa.Column('visitor_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'events', 'visitors', ['visitor_id'], ['id'])
    op.create_foreign_key(None, 'events', 'variants', ['variant_id'], ['id'])
    op.create_foreign_key(None, 'events', 'experiments', ['experiment_id'], ['id'])
    op.drop_column('events', 'user_id')
    op.add_column('visitors', sa.Column('experiment_id', sa.UUID(), nullable=False))
    op.add_column('visitors', sa.Column('variant_id', sa.UUID(), nullable=False))
    op.add_column('visitors', sa.Column('fingerprint', sa.String(), nullable=False))
    op.create_index(op.f('ix_visitors_fingerprint'), 'visitors', ['fingerprint'], unique=False)
    op.create_foreign_key(None, 'visitors', 'experiments', ['experiment_id'], ['id'])
    op.create_foreign_key(None, 'visitors', 'variants', ['variant_id'], ['id'])
    op.drop_column('visitors', 'variant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('variant', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.drop_index(op.f('ix_visitors_fingerprint'), table_name='visitors')
    op.drop_column('visitors', 'fingerprint')
    op.drop_column('visitors', 'variant_id')
    op.drop_column('visitors', 'experiment_id')
    op.add_column('events', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'visitor_id')
    op.drop_column('events', 'variant_id')
    op.drop_column('events', 'experiment_id')
    op.add_column('conversions', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conversions', type_='foreignkey')
    op.drop_constraint(None, 'conversions', type_='foreignkey')
    op.drop_constraint(None, 'conversions', type_='foreignkey')
    op.drop_column('conversions', 'goal')
    op.drop_column('conversions', 'visitor_id')
    op.drop_column('conversions', 'variant_id')
    op.drop_column('conversions', 'experiment_id')
    # ### end Alembic commands ###
